[package]
name = "runpod-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
reqwest = { version = "0.11.*", features = ["json"] }
serde = { version="1.0.*", features=["derive"] }
serde_json = "1.0.114"
tokio = "1.36.0"
